/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaJugadores.java
 *
 * Created on 11-03-2011, 12:35:10 AM
 */
package uno_danjohwen;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.image.RenderedImage;


/**
 *
 * @author Wendy
 */
public class PantallaJugadores extends javax.swing.JFrame {
    
    protected Jugadores jugador=new Jugadores();    
    
    /** Creates new form PantallaJugadores */
    public PantallaJugadores() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtnombre.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtedad = new javax.swing.JTextField();
        cbgenero = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        PanelFoto = new javax.swing.JPanel();
        lblfoto = new javax.swing.JLabel();
        btnsubirfoto = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(uno_danjohwen.UNO_DanJohWenApp.class).getContext().getResourceMap(PantallaJugadores.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setName("Form"); // NOI18N

        jPanel2.setBackground(resourceMap.getColor("jPanel2.background")); // NOI18N
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(null);

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(170, 30, 180, 29);

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(70, 80, 47, 15);

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel2.add(jLabel3);
        jLabel3.setBounds(70, 110, 30, 15);

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(70, 150, 43, 15);

        txtnombre.setText(resourceMap.getString("txtnombre.text")); // NOI18N
        txtnombre.setName("txtnombre"); // NOI18N
        jPanel2.add(txtnombre);
        txtnombre.setBounds(160, 80, 133, 20);

        txtedad.setText(resourceMap.getString("txtedad.text")); // NOI18N
        txtedad.setName("txtedad"); // NOI18N
        jPanel2.add(txtedad);
        txtedad.setBounds(160, 110, 67, 20);

        cbgenero.setFont(resourceMap.getFont("cbgenero.font")); // NOI18N
        cbgenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));
        cbgenero.setName("cbgenero"); // NOI18N
        jPanel2.add(cbgenero);
        cbgenero.setBounds(160, 150, 86, 21);

        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(80, 200, 81, 23);

        btnAtras.setFont(resourceMap.getFont("btnAtras.font")); // NOI18N
        btnAtras.setText(resourceMap.getString("btnAtras.text")); // NOI18N
        btnAtras.setName("btnAtras"); // NOI18N
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });
        jPanel2.add(btnAtras);
        btnAtras.setBounds(200, 200, 65, 23);

        PanelFoto.setBorder(javax.swing.BorderFactory.createLineBorder(resourceMap.getColor("PanelFoto.border.lineColor"))); // NOI18N
        PanelFoto.setName("PanelFoto"); // NOI18N

        lblfoto.setText(resourceMap.getString("lblfoto.text")); // NOI18N
        lblfoto.setName("lblfoto"); // NOI18N

        javax.swing.GroupLayout PanelFotoLayout = new javax.swing.GroupLayout(PanelFoto);
        PanelFoto.setLayout(PanelFotoLayout);
        PanelFotoLayout.setHorizontalGroup(
            PanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblfoto, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
        );
        PanelFotoLayout.setVerticalGroup(
            PanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblfoto, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
        );

        jPanel2.add(PanelFoto);
        PanelFoto.setBounds(330, 70, 135, 119);

        btnsubirfoto.setFont(resourceMap.getFont("btnsubirfoto.font")); // NOI18N
        btnsubirfoto.setText(resourceMap.getString("btnsubirfoto.text")); // NOI18N
        btnsubirfoto.setName("btnsubirfoto"); // NOI18N
        btnsubirfoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsubirfotoMouseClicked(evt);
            }
        });
        jPanel2.add(btnsubirfoto);
        btnsubirfoto.setBounds(330, 200, 135, 23);

        jButton2.setFont(resourceMap.getFont("jButton2.font")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(60, 290, 121, 23);

        jLabel5.setIcon(resourceMap.getIcon("jLabel5.icon")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 535, 334);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    // Guardar Jugador
    
    char gen;
    int edad;
    String nom=txtnombre.getText();
    String genero= (String)cbgenero.getSelectedItem();
    String age=txtedad.getText();    
    
    if(!nom.isEmpty() && !genero.isEmpty()){
        if(!txtedad.getText().matches( "\\d{1,2}" ))
            JOptionPane.showMessageDialog(this, "Debes ingresar tu edad en números enteros y no pueden ser más de 2 digitos!!" ); 
        else{
            edad=Integer.parseInt(txtedad.getText());            
            
            if(genero.equalsIgnoreCase("Masculino"))
                gen='M';
            else
                gen='F';

             
                //jugadores[0]=new Jugadores(txtnombre.getText(),edad,gen);
         try{
             if(jugador.CrearJugador(nom,edad,gen)){
                irPantallaLogin();
             }

         }
         catch(Exception e){
             JOptionPane.showMessageDialog(this, "ERROR: "+e.getMessage());
         }       
           
       }
    }
    else{
        JOptionPane.showMessageDialog( this, "No puedes dejar campos vacios!!" );
    }    
    
}//GEN-LAST:event_jButton1MouseClicked

private void irPantallaLogin(){
    PantallaLogin p= new PantallaLogin(0);
    p.setVisible(true);
    this.dispose();
}

private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
// TODO add your handling code here:
    irPantallaLogin();
}//GEN-LAST:event_btnAtrasMouseClicked

private void btnsubirfotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsubirfotoMouseClicked
// TODO add your handling code here:
    ImageIcon foto= this.getFoto();
    if(foto !=null){
        this.lblfoto.setIcon(foto);
        
    }
    else{
        JOptionPane.showMessageDialog(this, "Ocurrio un error");
    }
}//GEN-LAST:event_btnsubirfotoMouseClicked

private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
// TODO add your handling code here:
    
    PantallaInicio p= new PantallaInicio();
    p.setVisible(true);
    this.dispose();
    
}//GEN-LAST:event_jButton2MouseClicked

 private ImageIcon getFoto(){
        JFileChooser chooser= new JFileChooser();
        
        chooser.setDialogTitle("Foto Jugador");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
   
        int opcion=chooser.showOpenDialog(this);
        
        if(opcion==JFileChooser.APPROVE_OPTION){
            String fotoPath=chooser.getSelectedFile().getAbsolutePath();
            String fotoName=chooser.getSelectedFile().getName();
            String ext = chooser.getSelectedFile().getName().substring(chooser.getSelectedFile().getName().lastIndexOf("."));
            
            ImageIcon foto= new ImageIcon(fotoPath);
            RenderedImage imagenR;
           
            ImageIcon fotoReal= new ImageIcon(foto.getImage().getScaledInstance(lblfoto.getWidth(), lblfoto.getHeight(), Image.SCALE_DEFAULT));
            
            //ImageIO.write(imagenR, ext, new File(fotoName));
            
            return fotoReal;
        }
        
        return null;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaJugadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PantallaJugadores().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFoto;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnsubirfoto;
    private javax.swing.JComboBox cbgenero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblfoto;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
