/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaLogin.java
 *
 * Created on 11-06-2011, 01:48:15 AM
 */
package uno_danjohwen;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Wendy
 */
public class PantallaLogin extends javax.swing.JFrame {
    protected int Jugador=1;
    protected Jugadores[] jugadores=new Jugadores[2];
    private Jugadores j= new Jugadores();
    /** Creates new form PantallaLogin */
    public PantallaLogin() {
        initComponents();
        
        this.setLocationRelativeTo(null); 
        
        try{
            ArrayList<Jugadores> players=j.listarJugadores();
            DefaultListModel modelo = new DefaultListModel();
            for(Jugadores player:players){                
                modelo.add(player.Codigo-1, player.Nombre);
            }
            PlayersList.setModel(modelo);        
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"ERROR: "+ e);
        }
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        lblJugador = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PlayersList = new javax.swing.JList();
        CrearJugador = new javax.swing.JButton();
        EliminarJugador = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(uno_danjohwen.UNO_DanJohWenApp.class).getContext().getResourceMap(PantallaLogin.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N

        jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        btnEntrar.setFont(resourceMap.getFont("btnEntrar.font")); // NOI18N
        btnEntrar.setText(resourceMap.getString("btnEntrar.text")); // NOI18N
        btnEntrar.setName("btnEntrar"); // NOI18N
        btnEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntrarMouseClicked(evt);
            }
        });

        lblJugador.setFont(resourceMap.getFont("lblJugador.font")); // NOI18N
        lblJugador.setText(resourceMap.getString("lblJugador.text")); // NOI18N
        lblJugador.setName("lblJugador"); // NOI18N

        jButton2.setFont(resourceMap.getFont("jButton2.font")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        PlayersList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        PlayersList.setName("PlayersList"); // NOI18N
        jScrollPane1.setViewportView(PlayersList);

        CrearJugador.setFont(resourceMap.getFont("CrearJugador.font")); // NOI18N
        CrearJugador.setText(resourceMap.getString("CrearJugador.text")); // NOI18N
        CrearJugador.setName("CrearJugador"); // NOI18N
        CrearJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearJugadorMouseClicked(evt);
            }
        });

        EliminarJugador.setFont(resourceMap.getFont("EliminarJugador.font")); // NOI18N
        EliminarJugador.setText(resourceMap.getString("EliminarJugador.text")); // NOI18N
        EliminarJugador.setName("EliminarJugador"); // NOI18N
        EliminarJugador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarJugadorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(130, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EliminarJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2)
                                    .addComponent(CrearJugador))
                                .addGap(19, 19, 19))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(lblJugador)))
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addGap(114, 114, 114))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(lblJugador)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CrearJugador)
                            .addComponent(btnEntrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(EliminarJugador)))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
// TODO add your handling code here:
    PantallaInicio p= new PantallaInicio();
    p.setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton2MouseClicked

private void btnEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntrarMouseClicked
// TODO add your handling code here:
    
      int cod= PlayersList.getSelectedIndex();

      try{
          if(Jugador==1){
            jugadores[0]=j.ObtenerDatosJugador(cod+1);
            lblJugador.setText("Jugador No. 2");
            Jugador=2;
        }
        else{
            jugadores[1]=j.ObtenerDatosJugador(cod+1);
            PantallaJuego p= new PantallaJuego(jugadores);
            p.setVisible(true);
            this.dispose();
        }
      }catch(Exception e){
          JOptionPane.showMessageDialog(null,"ERROR: "+ e);
      }
}//GEN-LAST:event_btnEntrarMouseClicked

private void CrearJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearJugadorMouseClicked
// TODO add your handling code here:
    PantallaJugadores PJ= new PantallaJugadores();
    PJ.setVisible(true);
    this.dispose();
}//GEN-LAST:event_CrearJugadorMouseClicked

private void EliminarJugadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarJugadorMouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_EliminarJugadorMouseClicked

//private Jugadores buscarJugador(String nom, String pass){
//   String linea,nombre,password;
//   char genero;
//   int cod,edad;
//   String path=System.getProperty("user.dir");
//   String dirArchivo=path+"\\Jugadores.uno";
//   File archivo= new File(dirArchivo);
//   if(archivo.exists()){
//       try{
//           
//          BufferedReader br= new BufferedReader(new FileReader(dirArchivo));
//          
//          while((linea= br.readLine())!=null) {
//              if(!linea.isEmpty()){
//                  String[]temp=linea.split(";");
//                  cod=Integer.valueOf(temp[0]);
//                  nombre=temp[1];
//                  edad=Integer.valueOf(temp[2]);
//                  genero=temp[3].charAt(0);
//                  password=temp[4];
//                  if(nombre.equals(nom)&&password.equals(pass)){
//                      Jugadores jugador=new Jugadores(cod,nombre,edad,genero);
//                      return jugador;
//                  }
//              }
//              else{
//                  break;
//              } 
//          }
//          return null;
//       
//       }
//        catch(Exception e){
//          JOptionPane.showMessageDialog(this, e); 
//       }
//       
//   }
//    return null;
//}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PantallaLogin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearJugador;
    private javax.swing.JButton EliminarJugador;
    private javax.swing.JList PlayersList;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJugador;
    // End of variables declaration//GEN-END:variables
}
