/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PartidasGuardadas.java
 *
 * Created on 12-06-2011, 01:27:00 AM
 */
package uno_danjohwen;

import java.io.File;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Wendy
 */
public class PartidasGuardadas extends javax.swing.JFrame {
    File partidas= new File("Partidas");      
    Jugadores[] jugadores=new Jugadores[2];
    Jugadores[] jugadores2= new Jugadores[2];
    /** Creates new form PartidasGuardadas */
    public PartidasGuardadas(){
        
    }
    
    public PartidasGuardadas(Jugadores[] players) {
        initComponents();
        jugadores=players;       
        if(partidas.isDirectory()){
            File archivos[]=partidas.listFiles();
            DefaultListModel modelo = new DefaultListModel();  
            
            for(File arch:archivos){
                if(!arch.getName().equalsIgnoreCase("CodigoPartidas.uno") && !arch.getName().equalsIgnoreCase("Historial.uno"))                    
                    modelo.addElement(arch.getName());
            }
            
            ListaPartidas.setModel(modelo);            
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaPartidas = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        getContentPane().setLayout(null);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(null);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(uno_danjohwen.UNO_DanJohWenApp.class).getContext().getResourceMap(PartidasGuardadas.class);
        jButton2.setFont(resourceMap.getFont("jButton2.font")); // NOI18N
        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(60, 290, 87, 25);

        jButton1.setFont(resourceMap.getFont("jButton1.font")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(210, 270, 110, 25);

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 30, 210, 29);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        ListaPartidas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListaPartidas.setName("ListaPartidas"); // NOI18N
        ListaPartidas.setOpaque(false);
        jScrollPane1.setViewportView(ListaPartidas);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(180, 80, 181, 180);

        jLabel2.setIcon(resourceMap.getIcon("jLabel2.icon")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 535, 334);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 535, 334);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
    
    //Boton de atrás
    MenuPartidas MP=new MenuPartidas();
    MP.setVisible(true);
    this.dispose();
}//GEN-LAST:event_jButton2MouseClicked

private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
   
    //Boton de Reanudar
    String archivo=ListaPartidas.getSelectedValue().toString();
        try {
            RandomAccessFile partida= new RandomAccessFile("Partidas\\"+archivo,"rw");
            
            ArrayList<Cartas> CartasJ1= new ArrayList(),CartasJ2= new ArrayList(),CartasCentro= new ArrayList();
            String CartaCentro;

            int codJ1=partida.readInt();
            int puntosJ1=partida.readInt();
            int cantCartasJ1=partida.readInt();

            for(int i=0;i<cantCartasJ1;i++){
                String carta=partida.readUTF();
                String color=carta.substring(0, carta.length()-1);
                int NumColor=0;
                
                if(color.equalsIgnoreCase("Amarillo"))
                      NumColor=0;
                else if(color.equalsIgnoreCase("Azul"))
                      NumColor=1;
                else if(color.equalsIgnoreCase("Rojo"))
                      NumColor=2;
                else if(color.equalsIgnoreCase("Verde"))
                      NumColor=3;
                else
                      NumColor=4;
                
                try{
                      int NumCarta=Integer.valueOf(carta.substring(carta.length()-1,carta.length()));                      
                      CartasJ1.add(new CartasNumericas(NumColor,NumCarta));                     
                }
                catch(Exception ex){
                      char centerCardTipo=carta.charAt(carta.length()-1);
                      int tipo=0;
                      switch(centerCardTipo){
                          case 'T':
                              tipo=0;                       
                              break;
                          case 'R':
                              tipo=1;
                              break;
                          case 'S':
                              tipo=2;
                              break;
                          case 'C':
                              tipo=3;
                              break;
                          case 'M':
                              tipo=4;
                              break;
                      }
                      CartasJ1.add(new CartasEspeciales(NumColor,tipo));
                }
            }

            int codJ2=partida.readInt();
            int puntosJ2=partida.readInt();
            int cantCartasJ2=partida.readInt();

            for(int i=0;i<cantCartasJ2;i++){
                String carta=partida.readUTF();
                String color=carta.substring(0, carta.length()-1);
                int NumColor=0;
                
                if(color.equalsIgnoreCase("Amarillo"))
                      NumColor=0;
                else if(color.equalsIgnoreCase("Azul"))
                      NumColor=1;
                else if(color.equalsIgnoreCase("Rojo"))
                      NumColor=2;
                else if(color.equalsIgnoreCase("Verde"))
                      NumColor=3;
                else
                      NumColor=4;
                
                try{
                      int NumCarta=Integer.valueOf(carta.substring(carta.length()-1,carta.length()));                      
                      CartasJ2.add(new CartasNumericas(NumColor,NumCarta));                     
                }
                catch(Exception ex){
                      char centerCardTipo=carta.charAt(carta.length()-1);
                      int tipo=0;
                      switch(centerCardTipo){
                          case 'T':
                              tipo=0;                       
                              break;
                          case 'R':
                              tipo=1;
                              break;
                          case 'S':
                              tipo=2;
                              break;
                          case 'C':
                              tipo=3;
                              break;
                          case 'M':
                              tipo=4;
                              break;
                      }
                      CartasJ2.add(new CartasEspeciales(NumColor,tipo));
                }
            }

            CartaCentro=partida.readUTF();

            int cantCartasCentro=partida.readInt();

            for(int i=0;i<cantCartasCentro;i++){
                String carta=partida.readUTF();
                String color=carta.substring(0, carta.length()-1);
                int NumColor=0;
                
                if(color.equalsIgnoreCase("Amarillo"))
                      NumColor=0;
                else if(color.equalsIgnoreCase("Azul"))
                      NumColor=1;
                else if(color.equalsIgnoreCase("Rojo"))
                      NumColor=2;
                else if(color.equalsIgnoreCase("Verde"))
                      NumColor=3;
                else
                      NumColor=4;
                
                try{
                      int NumCarta=Integer.valueOf(carta.substring(carta.length()-1,carta.length()));                      
                      CartasCentro.add(new CartasNumericas(NumColor,NumCarta));                     
                }
                catch(Exception ex){
                      char centerCardTipo=carta.charAt(carta.length()-1);
                      int tipo=0;
                      switch(centerCardTipo){
                          case 'T':
                              tipo=0;                       
                              break;
                          case 'S':
                              tipo=1;
                              break;
                          case 'R':
                              tipo=2;
                              break;
                          case 'C':
                              tipo=3;
                              break;
                          case 'M':
                              tipo=4;
                              break;
                      }
                      CartasCentro.add(new CartasEspeciales(NumColor,tipo));
                }
            }
            
            int turno=partida.readInt();
            
            if(codJ1==jugadores[0].Codigo || codJ1==jugadores[1].Codigo){
                if(codJ2==jugadores[0].Codigo || codJ2==jugadores[1].Codigo){
                    
                    jugadores2[0]=codJ1==jugadores[0].Codigo?jugadores[0]:jugadores[1];
                    jugadores2[1]=codJ2==jugadores[0].Codigo?jugadores[0]:jugadores[1];
                    
                    partida.close();
                    
                    PantallaJuego PJ= new PantallaJuego( CartasJ1, CartasJ2, CartasCentro,jugadores2, CartaCentro,turno,puntosJ1,puntosJ2,archivo);
                    PJ.setVisible(true);
                    this.dispose();
                }
                else{
                 JOptionPane.showMessageDialog(this,"ERROR: La partida no pertenece a los jugadores elegidos!!");
                }
            }
            else{
                 JOptionPane.showMessageDialog(this,"ERROR: La partida no pertenece a los jugadores elegidos!!");
            }
           
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this,"ERROR: "+ ex);          
        }
}//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartidasGuardadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartidasGuardadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartidasGuardadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartidasGuardadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PartidasGuardadas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList ListaPartidas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
